# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('title', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('src', models.CharField(max_length=20)),
                ('pic', models.URLField()),
                ('weburl', models.URLField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
