# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-29 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='news',
            name='weburl',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
