# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-30 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('blog', '0003_auto_20170429_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('click_history', models.TextField()),
                ('label', models.CharField(max_length=200)),
            ],
        ),
    ]
